harlotsphoenix/urls.py
from django.contrib import admin
from django.urls import path, include
from phoenix.admin import admin_site
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('phoenix.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin_site.urls),
]

phoenix/urls.py
from django.urls import path
from . import views, print_views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:session_id>/', views.session, name='session'),
    path('<int:session_id>/print', print_views.print_session, name='print_session'),
    path('<int:session_id>/record/', views.record_attendee, name='record_attendee'),
    path('attendance/<int:attendee_id>/delete/', views.delete_attendee, name='delete_attendee'),
    path('bubbles/<bubble>/ical.ics', views.ical, name='ical')
]

phoenix/models.py
from django.db import models


class Bubble(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Member(models.Model):
    legal_name = models.CharField(max_length=200)
    locale = models.CharField(max_length=200)
    contact_number = models.CharField(max_length=100)
    bubble = models.ForeignKey('Bubble', on_delete=models.CASCADE)

    class Meta:
        ordering = ['legal_name']

    def __str__(self):
        return self.legal_name


class Session(models.Model):
    time = models.DateTimeField()
    place = models.CharField(max_length=200)
    bubble = models.ForeignKey('Bubble', on_delete=models.CASCADE)
    attendees = models.ManyToManyField('Member', through='SessionAttendance')
    warning_sent = models.BooleanField(default=False)
    stats_uploaded = models.BooleanField(default=False)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return f'Bubble {self.bubble} session on {self.time.ctime()} at {self.place}'


class SessionAttendance(models.Model):
    member = models.ForeignKey('Member', on_delete=models.CASCADE)
    session = models.ForeignKey('Session', on_delete=models.CASCADE)
    temperature = models.FloatField(null=True)
    test_pass = models.BooleanField(default=False)

phoenix/views.py
from datetime import timedelta

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from phoenix.models import Session, Member, SessionAttendance, Bubble


@login_required
def index(request):
    now = timezone.now()
    # future is everything beyond now (but let's say yeseterday)
    margin = timedelta(hours=settings.SEND_MAIL_DEADLINE_HOURS)
    lower_horizon = now - margin
    sessions = Session.objects.filter(time__gte=lower_horizon).order_by('time')
    previous_sessions = Session.objects.filter(time__lt=lower_horizon)
    ctx = dict(
        sessions=sessions,
        past_sessions=previous_sessions
    )
    return render(request, 'phoenix/sessions.html', ctx)


@login_required
def session(request, session_id: int):
    s: Session = get_object_or_404(Session, pk=session_id)
    ctx = dict(
        session=s
    )
    return render(request, 'phoenix/session.html', ctx)


@login_required
def record_attendee(request, session_id: int):
    s: Session = get_object_or_404(Session, pk=session_id)
    ctx = dict(
        session=s,
        members=s.bubble.member_set.exclude(pk__in=s.attendees.all())
    )
    if request.method == 'POST':
        m: Member = get_object_or_404(Member, pk=request.POST['member'])
        t = request.POST['temperature'] or None
        if t:
            t = int(t)
        test_passed = 'test_passed' in request.POST
        sa, new = SessionAttendance.objects.update_or_create(member=m, session=s, temperature=t, test_pass=test_passed)
        return HttpResponseRedirect(reverse('session', args=[session_id]))

    return render(request, 'phoenix/record.html', ctx)


@login_required
def delete_attendee(request, attendee_id: int):
    sa = get_object_or_404(SessionAttendance, pk=attendee_id)
    session_id = sa.session_id
    sa.delete()
    return HttpResponseRedirect(reverse('session', args=[session_id]))


def format_ical_date_string(dt):
    return dt.strftime('%Y%m%dT%H%M%SZ')


EVENT_DURATION = timezone.timedelta(0, 0, 0, 0, 0, 2)


def ical(request, bubble: str):
    b = get_object_or_404(Bubble, name=bubble)
    resp = HttpResponse(content_type='text/calendar')

    resp.write('BEGIN:VCALENDAR\n')
    resp.write('VERSION:2.0\n')
    resp.write('PRODID:-//RDEC//NONSGML v1.0//EN\n')
    now = timezone.now()

    then = now - timedelta(days=1)

    events = Session.objects.filter(bubble=b).filter(time__gt=then).order_by('time')
    for e in events:

        end = e.time + EVENT_DURATION

        resp.write('BEGIN:VEVENT\n')
        resp.write('UID:{}@{}\n'.format(e.pk, request.get_host()))
        resp.write('DTSTAMP:{}\n'.format(format_ical_date_string(e.last_modified)))
        resp.write('DTSTART:{}\n'.format(format_ical_date_string(e.time)))
        resp.write('DTEND:{}\n'.format(format_ical_date_string(end)))
        resp.write('SUMMARY:{} ({})\n'.format(f'{settings.PHOENIX_NAME} Bubble {bubble} Session', e.place))

        resp.write('END:VEVENT\n')

    resp.write('END:VCALENDAR\n')
    return resp

templates/phoenix/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css'  %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
      <link rel="shortcut icon" type='image/png' href="{% static 'rainbow.png' %}">
    <link rel="icon" type='image/png' href="{% static 'rainbow.png' %}">
      <style type="text/css">
          body {
              font-family: 'Source Sans Pro', sans-serif;
          }
      </style>
    <title>{{ PHOENIX_NAME }} :: Phoenix</title>
  </head>
  <body>



    <div class="container-fluid mt-3 mb-3">
    <h1 style="padding-bottom: 1em;"><a href="{% url 'index' %}">🌈</a>PHOENIX | {{ PHOENIX_NAME}}</h1>
        {% block content %}
        {% endblock content %}
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>

  </body>
</html>

templates/phoenix/record.html
{% extends 'phoenix/session_base.html' %}
{% block sessioncontent %}

    <form action="{% url 'record_attendee' session.id %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="member" class="form-label">Attendee</label>
            <select id="member" name="member" class="form-select" aria-label="Member" aria-describedby="memberHelp">
                {% for member in members %}
                    <option value="{{ member.id }}">{{ member.legal_name }}</option>
                {% endfor %}
            </select>
            <div id="memberHelp" class="form-text">Only members of the appropriate bubble who are not already recorded
                in this session are shown.
            </div>
        </div>
        <div class="mb-3">
            <label for="temperature" class="form-label">Temperature</label>
            <input type="number" class="form-control" id="temperature" name="temperature" aria-describedby="tempHelp">
             <div id="tempHelp" class="form-text">Optional.
            </div>
        </div>

        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="test_passed" name="test_passed">
            <label class="form-check-label" for="test_passed">
                Temperature Check Passed?
            </label>
        </div>

    <p>&nbsp;</p>

        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
    </form>
{% endblock %}

templates/phoenix/session.html
{% extends 'phoenix/session_base.html' %}
{% block sessioncontent %}
    <h4>Actions</h4>
    <a class="btn btn-primary btn-sm" href="{% url 'record_attendee' session.id %}" role="button">Record Attendee...</a>
    <a class="btn btn-primary btn-sm" href="{% url 'print_session' session.id %}" role="button">Download PDF...</a>
    <a class="btn btn-primary btn-sm disabled" href="#" role="button">Submit to BRSF...</a>

    <p>&nbsp;</p>
    <h4>Attendees</h4>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Temp Check Passed?</th>
            <th scope="col">Temperature</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for attendee in session.sessionattendance_set.all %}
            <tr>
                <th scope="row">
                    {{ attendee.member.legal_name }}
                </th>
                <td>
                    {% if attendee.test_pass %}
                        &checkmark;
                    {% else %}
                        &cross;
                    {% endif %}

                </td>
                <td>
                    {{ attendee.temperature|default_if_none:"--" }}
                </td>
                <td>
                    <a class="btn btn-primary btn-sm" href="{% url 'delete_attendee' attendee_id=attendee.id %}" role="button">Delete...</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/phoenix/session_base.html
{% extends 'phoenix/base.html' %}
{% block content %}
    <h2 style="padding-bottom: 0.5em;"><a href="{% url 'session' session.id %}">📅</a> {{ session.time }} at {{ session.place }} <span class="badge rounded-pill bg-primary">Bubble {{ session.bubble }}</span>
    </h2>

{% block sessioncontent %}
{% endblock %}
{% endblock%}

templates/phoenix/sessions.html
{% extends 'phoenix/base.html' %}
{% block content %}
    <h2>Sessions</h2>
    <h3>Upcoming</h3>
    <table class="table">
    <thead>
    <tr>
        <th scope="col">Date</th>
        <th scope="col">Venue</th>
        <th scope="col">Bubble</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for session in sessions %}
        <tr>
        <th scope="row">
            {{ session.time }}
        </th>
        <td>
            {{ session.place }}
        </td>
          <td>
            {{ session.bubble }}
        </td>
          <td>
              <a class="btn btn-primary btn-sm" href="{% url 'session' session.id  %}" role="button">View...</a>
        </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>

    <h3>Previous</h3>
        <table class="table">
    <thead>
    <tr>
        <th scope="col">Date</th>
        <th scope="col">Venue</th>
        <th scope="col">Bubble</th>
        <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    {% for session in sessions %}
        <tr>
        <th scope="row">
            {{ session.time }}
        </th>
        <td>
            {{ session.place }}
        </td>
          <td>
            {{ session.bubble }}
        </td>
          <td>
              <a class="btn btn-primary btn-sm" href="{% url 'session' session.id  %}" role="button">View...</a>
        </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}